# This is logger config file

LogLevel = "trace"

[FileWriter]
    On = true
    LogPath = "./log/golang_common.inf.log"
    RotateLogPath = "./log/golang_common.inf.log"
    WfLogPath = "./log/golang_common.wf.log"
    RotateWfLogPath = "./log/golang_common.wf.log"

[ConsoleWriter]
    On = true
    Color = true
